services:
  db:
    image: postgres:16
    container_name: qr_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qr_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    sysctls:
      - net.ipv4.ping_group_range=0 0

  backend:
    build: ./backend
    container_name: qr_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: qr_frontend
    restart: always
    ports:
      - "3000:3000"

volumes:
  postgres_data:
